config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "user/index" => "user#index"
  get "photo/index/:id" => "photo#index" , as: "user_photos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all
    @user_all = User.all
  end
  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PS2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PhotoSite</title>
  <style>
    #p01 {
      font-size: 15pt;
      font-family: times new roman;
      border: 1px solid powderblue;
    }
    #p02 {
      font-size: 15pt;
      font-family: times new roman;
    }
  </style>
</head>
<body>

  <h1 style="font-size: 30pt">Photo page</h1>

  <p id="p02"><u>Photo of</u> :- <b><i><%= link_to @user.first_name %> <%= link_to @user.last_name %></i></b></p>
  <% @photos.each do |photo| %>
    <%= image_tag("/assets/#{photo.file_name}") %>
  <p id="p02"> <u> Photo created on</u> :- <b><i><%= photo.date_time %></i></b></p>

    <% @comments.where("photo_id=?",photo.id).each do |comment| %>

    <p id="p01"><b><i> <u>Comment</u> :- <%= comment.comment_text %></i></b></p>
    <p id="p01"><b><i> <u>Created on</u> :- <%= comment.date_time %></i></b></p>
    <p id="p01"><b><i> <u>Posted by</u> :- <%= link_to display_name(comment.user_id) , user_photos_path(comment.user_id) %></i></b></p>

    <% end %>

  <%end%>
  </body>
</html>

app/views/user/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title >PhotoSite</title>
  <style>
    table {
      border: 1px solid black;
      width: 80%;
    }
    th, td {
      border: 1px solid black;
      padding: 15px;
      color: red;
      font-size: 20pt;
      text-align: left;
    }
  </style>
</head>
<body>
<marquee><h1 style="color:Black; font-size:30pt">PhotoSite</h1></marquee>
<table>
  <caption style="color:Blue; font-size:25pt"><b>List of Users</b></caption>
  <thead>
  <th>User</th>
  <th>First</th>
  <th>Last</th>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.id, user_photos_path(user.id) %></td>
      <td><%= link_to user.first_name, user_photos_path(user.id) %></td>
      <td><%= link_to user.last_name, user_photos_path(user.id) %></td>
    </tr>
  <% end %>
</table>
</body>
</html>